# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo-configmap

data:
  DB_URL: mongodb+srv://romany:rafie208@cluster0.mc0cc.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  DB_SERVER: "auth-mongo-svc"
  DB_BASE_URL_BOOKING_MS: "mongodb+srv://"
  DB_SERVER_BOOKING_MS: "cluster0.mc0cc.mongodb.net/tickets-app?retryWrites=true&w=majority"
  DB_PORT_BOOKING_MS: "27017"
