apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: tickets.io
    http:
      paths:
      - pathType: Prefix
        path: "/login"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001
      - pathType: Prefix
        path: "/login/submit"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001
      - pathType: Prefix
        path: "/signup"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001
      - pathType: Prefix
        path: "/signup/submit"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001
      - pathType: Prefix
        path: "/signout"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: auth-ms
            port: 
              number: 5001