# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
data:
  DB_Password: cmFmaWUyMDg=
  DB_USERNAME: cm9tYW55
# vars enctypted by using 
# echo -n '${url value}' | base64


# Note: 
# We can creste secrets by: 
# kubctel create secret generic {name od secret} --from-literal={key=value}