# Source: https://marioyepes.com/mongodb-express-using-docker/
# docxker-compose to run mongodb and express
#version # services #networks  # voulmes 

version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  
    volumes:
      -  mongodb-test:/data/db  # mount the mongodb-test data volume in the data/db directory
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN='true'
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  


networks:
  default:
    name: mongo-express-network

volumes:
  mongodb-test:
    driver: local


# docker volume create mongodb-test          # create a volume called mongodb-test
# docker volume ls                           # list volumes
# docker volume rm mongodb-test              # remove the volume
# docker volume inspect mongodb-test         # to see the volume's details

# docker run -d  --name mongodb -p 27017:27017 -v mongodb-test:/data/db mongo                # run mongo and mount the mongodb-test data volume in the data/db directory
